CREATE TABLE TRACKER.WORKOUT (
    NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    PROGRAM_NAME VARCHAR(50) NOT NULL REFERENCES TRACKER.PROGRAM(NAME) ON DELETE CASCADE,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);