CREATE TABLE TRACKER.PROGRAM_DETAILS (
    PROGRAM_NAME VARCHAR(50) NOT NULL REFERENCES TRACKER.PROGRAM(NAME) ON DELETE CASCADE,
    WORKOUT_NAME VARCHAR(50) NOT NULL REFERENCES TRACKER.WORKOUT(NAME) ON DELETE CASCADE,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(PROGRAM_NAME, WORKOUT_NAME)
);