CREATE TABLE TRACKER.EXERCISE_DETAILS (
    EXERCISE_NAME VARCHAR(50) NOT NULL,
    BODY_PART VARCHAR(50) NOT NULL,
    LEVEL VARCHAR(10) NOT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(EXERCISE_NAME, BODY_PART)
);

ALTER TABLE TRACKER.EXERCISE_DETAILS
    ADD CONSTRAINT FK_EXERCISE_KEY 
    FOREIGN KEY(EXERCISE_NAME)
    REFERENCES TRACKER.EXERCISE(NAME);