CREATE TABLE TRACKER.BODY_PARTS (
    NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    REGION VARCHAR(50) NOT NULL,
    UPPER_OR_LOWER CHAR(5) NOT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);