CREATE TABLE TRACKER.WORKOUT_PERFORMED (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    SUBMITTED_ON DATE DEFAULT CURRENT_DATE NOT NULL,
    WORKOUT_NAME VARCHAR(50) NOT NULL REFERENCES TRACKER.WORKOUT(NAME) ON DELETE CASCADE,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);