CREATE TABLE TRACKER.SET_PERFORMED (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    WORKOUT_ID INTEGER NOT NULL REFERENCES TRACKER.WORKOUT_PERFORMED(ID) ON DELETE CASCADE,
    GROUP_ID SMALLINT NOT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
