CREATE TABLE TRACKER.SET_PERFORMED (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    EXERCISE_ID INTEGER NOT NULL REFERENCES TRACKER.EXERCISE_PERFORMED(ID) ON DELETE CASCADE,
    REPS SMALLINT NOT NULL,
    WEIGHT SMALLINT NOT NULL,
    REPS_IN_RESERVE DECIMAL DEFAULT 1,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
