CREATE TABLE TRACKER.EXERCISE_PERFORMED (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    SET_ID INTEGER NOT NULL REFERENCES TRACKER.SET_PERFORMED(ID) ON DELETE CASCADE,
    EXERCISE_NAME VARCHAR(50) NOT NULL REFERENCES TRACKER.EXERCISE(NAME),
    REPS SMALLINT NOT NULL,
    WEIGHT SMALLINT NOT NULL,
    REPS_IN_RESERVE DECIMAL DEFAULT 1,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
