CREATE TABLE TRACKER.DIET (
    DATE DATE DEFAULT CURRENT_DATE,
    CALORIES SMALLINT NOT NULL,
    PROTEIN SMALLINT DEFAULT NULL,
    CARBOHYDRATES SMALLINT DEFAULT NULL,
    FAT SMALLINT DEFAULT NULL,
    MICRONUTRIENTS JSONB DEFAULT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);