CREATE TABLE TRACKER.EXERCISE (
    EXERCISE VARCHAR(50) PRIMARY KEY NOT NULL,
    RATING SMALLINT, 
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);