CREATE TABLE TRACKER.NUTRITION (
    DATE DATE DEFAULT CURRENT_DATE PRIMARY KEY,
    CALORIES SMALLINT NOT NULL,
    PROTEIN SMALLINT,
    CARBOHYDRATE SMALLINT,
    FAT SMALLINT,
    MICRONUTRIENTS JSONB,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);