CREATE TABLE TRACKER.WORKOUT (
    WORKOUT_ID INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    DATE DATE DEFAULT CURRENT_DATE NOT NULL,
    EXERCISE VARCHAR(50) NOT NULL,
    SETS SMALLINT NOT NULL,
    REPS SMALLINT NOT NULL,
    WEIGHT SMALLINT NOT NULL,
    REPS_IN_RESERVE DECIMAL DEFAULT 1,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);