CREATE TABLE TRACKER.WORKOUT (
    WORKOUT_ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    EXERCISE VARCHAR(50),
    SETS TINYINT NOT NULL,
    REPS TINYINT NOT NULL,
    WEIGHT TINYINT NOT NULL,
    REPS_IN_RESERVE DECIMAL DEFAULT 1,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);