version: "3.9"
    
services:
  db:
    image: mtavarez/health-tracker-db:${DB_IMAGE_VERSION}
    volumes:
      - health-tracker-pg:/var/lib/postgresql/data
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  health-tracker-pg: {}
