// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: composition.sql

package queries

import (
	"context"
)

const deleteComposition = `-- name: DeleteComposition :exec
DELETE FROM tracker.composition
WHERE SUBMITTED_ON = $1
`

func (q *Queries) DeleteComposition(ctx context.Context, submittedOn string) error {
	_, err := q.db.ExecContext(ctx, deleteComposition, submittedOn)
	return err
}

const getCompositionDetails = `-- name: GetCompositionDetails :one
SELECT submitted_on, weight, bodyfat, neck, shoulders, left_bicep, right_bicep, left_tricep, right_tricep, left_forearm, right_forearm, chest, waist, left_quad, right_quad, left_calf, right_calf, cret_ts, updt_ts FROM tracker.composition
WHERE SUBMITTED_ON = $1 LIMIT 1
`

func (q *Queries) GetCompositionDetails(ctx context.Context, submittedOn string) (TrackerComposition, error) {
	row := q.db.QueryRowContext(ctx, getCompositionDetails, submittedOn)
	var i TrackerComposition
	err := row.Scan(
		&i.SubmittedOn,
		&i.Weight,
		&i.Bodyfat,
		&i.Neck,
		&i.Shoulders,
		&i.LeftBicep,
		&i.RightBicep,
		&i.LeftTricep,
		&i.RightTricep,
		&i.LeftForearm,
		&i.RightForearm,
		&i.Chest,
		&i.Waist,
		&i.LeftQuad,
		&i.RightQuad,
		&i.LeftCalf,
		&i.RightCalf,
		&i.CretTs,
		&i.UpdtTs,
	)
	return i, err
}

const submitComposition = `-- name: SubmitComposition :one
INSERT INTO tracker.composition (
  WEIGHT, BODYFAT
) VALUES (
  $1, $2
)
RETURNING submitted_on, weight, bodyfat, neck, shoulders, left_bicep, right_bicep, left_tricep, right_tricep, left_forearm, right_forearm, chest, waist, left_quad, right_quad, left_calf, right_calf, cret_ts, updt_ts
`

type SubmitCompositionParams struct {
	Weight  string
	Bodyfat string
}

func (q *Queries) SubmitComposition(ctx context.Context, arg SubmitCompositionParams) (TrackerComposition, error) {
	row := q.db.QueryRowContext(ctx, submitComposition, arg.Weight, arg.Bodyfat)
	var i TrackerComposition
	err := row.Scan(
		&i.SubmittedOn,
		&i.Weight,
		&i.Bodyfat,
		&i.Neck,
		&i.Shoulders,
		&i.LeftBicep,
		&i.RightBicep,
		&i.LeftTricep,
		&i.RightTricep,
		&i.LeftForearm,
		&i.RightForearm,
		&i.Chest,
		&i.Waist,
		&i.LeftQuad,
		&i.RightQuad,
		&i.LeftCalf,
		&i.RightCalf,
		&i.CretTs,
		&i.UpdtTs,
	)
	return i, err
}
