// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
	"github.com/thatstoasty/health-tracker/types"
)

type TrackerComposition struct {
	SubmittedOn  string `json:"date"`
	Weight       string `json:"weight"`
	Bodyfat      string `json:"bodyfat"`
	Neck         types.NullString `json:"neck,omitempty"`
	Shoulders    types.NullString `json:"shoulders,omitempty"`
	LeftBicep    types.NullString `json:"leftBicep,omitempty"`
	RightBicep   types.NullString `json:"rightBicep,omitempty"`
	LeftTricep   types.NullString `json:"leftTricep,omitempty"`
	RightTricep  types.NullString `json:"rightTricep,omitempty"`
	LeftForearm  types.NullString `json:"leftForearm,omitempty"`
	RightForearm types.NullString `json:"rightForearm,omitempty"`
	Chest        types.NullString `json:"chest,omitempty"`
	Waist        types.NullString `json:"waist,omitempty"`
	LeftQuad     types.NullString `json:"leftQuad,omitempty"`
	RightQuad    types.NullString `json:"rightQuad,omitempty"`
	LeftCalf     types.NullString `json:"leftCalf,omitempty"`
	RightCalf    types.NullString `json:"rightCalf,omitempty"`
	CretTs       sql.NullTime `json:"-"`
	UpdtTs       sql.NullTime `json:"-"`
}

type TrackerExercise struct {
	Name   string    `json:"name"`
	CretTs time.Time `json:"cretTs"`
	UpdtTs time.Time `json:"updtTs"`
}

type TrackerExerciseDetail struct {
	ExerciseName string    `json:"exerciseName"`
	BodyPart     string    `json:"bodyPart"`
	Level        string    `json:"level"`
	CretTs       time.Time `json:"cretTs"`
	UpdtTs       time.Time `json:"updtTs"`
}

type TrackerExercisePerformed struct {
	ID           int32     `json:"id"`
	WorkoutID    int32     `json:"workoutID"`
	GroupID      int16     `json:"groupID"`
	ExerciseName string    `json:"exerciseName"`
	CretTs       time.Time `json:"cretTs"`
	UpdtTs       time.Time `json:"updtTs"`
}

type TrackerNutrition struct {
	SubmittedOn    string                `json:"submittedOn"`
	Calories       int16                 `json:"calories"`
	Protein        sql.NullInt16         `json:"protein"`
	Carbohydrate   sql.NullInt16         `json:"carbohydrate"`
	Fat            sql.NullInt16         `json:"fat"`
	Micronutrients pqtype.NullRawMessage `json:"micronutrients"`
	CretTs         time.Time             `json:"cretTs"`
	UpdtTs         time.Time             `json:"updtTs"`
}

type TrackerProgram struct {
	Name   string    `json:"name"`
	CretTs time.Time `json:"cretTs"`
	UpdtTs time.Time `json:"updtTs"`
}

type TrackerProgramDetail struct {
	ProgramName string    `json:"programName"`
	WorkoutName string    `json:"workoutName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}

type TrackerSetPerformed struct {
	ID            int32          `json:"id"`
	ExerciseID    int32          `json:"exerciseID"`
	Reps          int16          `json:"reps"`
	Weight        int16          `json:"weight"`
	RepsInReserve types.NullString `json:"repsInReserve"`
	CretTs        time.Time      `json:"cretTs"`
	UpdtTs        time.Time      `json:"updtTs"`
}

type TrackerWorkout struct {
	Name        string    `json:"name"`
	ProgramName string    `json:"programName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}

type TrackerWorkoutDetail struct {
	WorkoutName  string    `json:"workoutName"`
	GroupID      int16     `json:"groupID"`
	ExerciseName string    `json:"exerciseName"`
	Sets         int16     `json:"sets"`
	Reps         int16     `json:"reps"`
	Weight       int16     `json:"weight"`
	CretTs       time.Time `json:"cretTs"`
	UpdtTs       time.Time `json:"updtTs"`
}

type TrackerWorkoutPerformed struct {
	ID          int32     `json:"id"`
	SubmittedOn time.Time `json:"submittedOn"`
	WorkoutName string    `json:"workoutName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}
