// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
	"github.com/thatstoasty/health-tracker/types"
)

type TrackerComposition struct {
	Date         string `json:"date"`
	Weight       string `json:"weight"`
	Bodyfat      string `json:"bodyfat"`
	Neck         types.NullString `json:"neck,omitempty"`
	Shoulders    types.NullString `json:"shoulders,omitempty"`
	LeftBicep    types.NullString `json:"leftBicep,omitempty"`
	RightBicep   types.NullString `json:"rightBicep,omitempty"`
	LeftTricep   types.NullString `json:"leftTricep,omitempty"`
	RightTricep  types.NullString `json:"rightTricep,omitempty"`
	LeftForearm  types.NullString `json:"leftForearm,omitempty"`
	RightForearm types.NullString `json:"rightForearm,omitempty"`
	Chest        types.NullString `json:"chest,omitempty"`
	Waist        types.NullString `json:"waist,omitempty"`
	LeftQuad     types.NullString `json:"leftQuad,omitempty"`
	RightQuad    types.NullString `json:"rightQuad,omitempty"`
	LeftCalf     types.NullString `json:"leftCalf,omitempty"`
	RightCalf    types.NullString `json:"rightCalf,omitempty"`
	CretTs       sql.NullTime `json:"-"`
	UpdtTs       sql.NullTime `json:"-"`
}

type TrackerExercise struct {
	Exercise string
	Rating   types.NullInt16
	CretTs   sql.NullTime
	UpdtTs   sql.NullTime
}

type TrackerExerciseDetail struct {
	Exercise string
	BodyPart string
	Level    string
}

type TrackerNutrition struct {
	Date           string
	Calories       int16
	Protein        types.NullInt16
	Carbohydrate   types.NullInt16
	Fat            types.NullInt16
	Micronutrients pqtype.NullRawMessage
	CretTs         sql.NullTime
	UpdtTs         sql.NullTime
}

type TrackerWorkout struct {
	WorkoutID     int32
	Date          time.Time
	Exercise      string
	Sets          int16
	Reps          int16
	Weight        int16
	RepsInReserve types.NullString
	CretTs        sql.NullTime
	UpdtTs        sql.NullTime
}
