// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: workout.sql

package queries

import (
	"context"
	"time"
)

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM tracker.workout
WHERE NAME = $1
`

func (q *Queries) DeleteWorkout(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, name)
	return err
}

const deleteWorkoutPerformed = `-- name: DeleteWorkoutPerformed :exec
DELETE FROM tracker.workout_performed
WHERE SUBMITTED_ON = $1
`

func (q *Queries) DeleteWorkoutPerformed(ctx context.Context, submittedOn time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutPerformed, submittedOn)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT name, program_name, cret_ts, updt_ts FROM tracker.workout
WHERE NAME = $1 LIMIT 1
`

func (q *Queries) GetWorkout(ctx context.Context, name string) (TrackerWorkout, error) {
	row := q.db.QueryRowContext(ctx, getWorkout, name)
	var i TrackerWorkout
	err := row.Scan(
		&i.Name,
		&i.ProgramName,
		&i.CretTs,
		&i.UpdtTs,
	)
	return i, err
}

const getWorkoutNames = `-- name: GetWorkoutNames :many
SELECT NAME FROM tracker.workout
LIMIT $1
`

func (q *Queries) GetWorkoutNames(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getWorkoutNames, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutPerformed = `-- name: GetWorkoutPerformed :one
SELECT id, submitted_on, workout_name, cret_ts, updt_ts FROM tracker.workout_performed
WHERE SUBMITTED_ON = $1 LIMIT 1
`

func (q *Queries) GetWorkoutPerformed(ctx context.Context, submittedOn time.Time) (TrackerWorkoutPerformed, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutPerformed, submittedOn)
	var i TrackerWorkoutPerformed
	err := row.Scan(
		&i.ID,
		&i.SubmittedOn,
		&i.WorkoutName,
		&i.CretTs,
		&i.UpdtTs,
	)
	return i, err
}
