CREATE TABLE TRACKER.WORKOUT (
    NAME VARCHAR(50) PRIMARY KEY NOT NULL,
    PROGRAM_NAME VARCHAR(50) NOT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE TRACKER.WORKOUT 
    ADD CONSTRAINT FK_PROGRAM_KEY 
    FOREIGN KEY(PROGRAM_NAME)
    REFERENCES TRACKER.PROGRAM(NAME);