CREATE TABLE TRACKER.PROGRAM_DETAILS (
    PROGRAM_NAME VARCHAR(50),
    WORKOUT_NAME VARCHAR(50),
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(PROGRAM_NAME, WORKOUT_NAME)
);

ALTER TABLE TRACKER.PROGRAM_DETAILS 
    ADD CONSTRAINT FK_PROGRAM_KEY 
    FOREIGN KEY(PROGRAM_NAME)
    REFERENCES TRACKER.PROGRAM(NAME);

ALTER TABLE TRACKER.PROGRAM_DETAILS 
    ADD CONSTRAINT FK_WORKOUT_KEY 
    FOREIGN KEY(WORKOUT_NAME)
    REFERENCES TRACKER.WORKOUT(NAME);