CREATE TABLE TRACKER.WORKOUT_DETAILS (
    WORKOUT_NAME VARCHAR(50) NOT NULL,
    GROUP_ID SMALLINT NOT NULL,
    EXERCISE_NAME VARCHAR(50) NOT NULL,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(WORKOUT_NAME, GROUP, EXERCISE_NAME)
);

ALTER TABLE TRACKER.WORKOUT_DETAILS
    ADD CONSTRAINT FK_WORKOUT_KEY 
    FOREIGN KEY(WORKOUT_NAME)
    REFERENCES TRACKER.WORKOUT(NAME);

ALTER TABLE TRACKER.EXERCISE
    ADD CONSTRAINT FK_EXERCISE_KEY 
    FOREIGN KEY(EXERCISE_NAME)
    REFERENCES TRACKER.EXERCISE(NAME);