CREATE TABLE TRACKER.NUTRITION (
    SUBMITTED_ON CHAR(10) DEFAULT CURRENT_DATE::CHAR(10) PRIMARY KEY NOT NULL,
    CALORIES SMALLINT NOT NULL,
    PROTEIN SMALLINT,
    CARBOHYDRATE SMALLINT,
    FAT SMALLINT,
    MICRONUTRIENTS JSONB,
    CRET_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);